# A small independent consumer; no MPFR computations or Metal device creation.
set(root "${LF_BINARY_DIR}/package-version-smoke")
set(prefix "${root}/install")
function(run_checked)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Package version check failed (${ARGV}):\n${out}\n${err}")
  endif()
endfunction()
run_checked("${CMAKE_COMMAND}" --install "${LF_BINARY_DIR}" --config "${LF_CONFIG}" --prefix "${prefix}")
set(common_args "-DLimbForge_DIR=${prefix}/${LF_LIBDIR}/cmake/LimbForge"
  "-DLF_EXPECTED_VERSION=${LF_VERSION}" "-DLF_EXPECTED_API=${LF_MAJOR}")
foreach(mode matched foreign)
  set(consumer "${root}/${mode}")
  set(foreign OFF)
  if(mode STREQUAL foreign)
    set(foreign ON)
  endif()
  run_checked("${CMAKE_COMMAND}" -S "${LF_SOURCE_DIR}/tests/package_consumer" -B "${consumer}"
    ${common_args} "-DLF_REQUIRED_VERSION=${LF_VERSION}" "-DLF_FOREIGN_HEADERS=${foreign}")
  run_checked("${CMAKE_COMMAND}" --build "${consumer}" --target package_consumer)
  run_checked("${consumer}/package_consumer")
endforeach()
math(EXPR next_major "${LF_MAJOR}+1")
math(EXPR next_patch "${LF_PATCH}+1")
foreach(request "${next_major}.0.0" "${LF_MAJOR}.${LF_MINOR}.${next_patch}" "${LF_MAJOR}.0.0...<${next_major}.0.0")
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${LF_SOURCE_DIR}/tests/package_consumer"
    -B "${root}/request-${request}" ${common_args} "-DLF_REQUIRED_VERSION=${request}"
    RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(request MATCHES "[.][.][.]")
    if(NOT result EQUAL 0)
      message(FATAL_ERROR "Compatible major range rejected:\n${out}\n${err}")
    endif()
  elseif(result EQUAL 0)
    message(FATAL_ERROR "Incompatible request ${request} was accepted")
  endif()
endforeach()
message(STATUS "Installed ${LF_VERSION}: consumer link, mismatch rejection and version constraints passed")
